# This is a GitHub workflow defining a set of jobs with a set of steps.
# ref: https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions
#
name: Integration tests

on:
  pull_request:
    paths-ignore:
      - "docs/**"
      - "**.md"
      - ".github/workflows/*"
      - "!.github/workflows/integration-test.yaml"
  push:
    paths-ignore:
      - "docs/**"
      - "**.md"
      - ".github/workflows/*"
      - "!.github/workflows/integration-test.yaml"
    branches-ignore:
      - "dependabot/**"
      - "pre-commit-ci-update-config"
  workflow_dispatch:

jobs:
  integration-tests:
    # integration tests run in a container,
    # not in the worker, so this version is not relevant to the tests
    # and can be the same for all tested versions
    runs-on: ubuntu-22.04

    name: ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "Debian 11, Py 3.9"
            distro_image: "debian:11"
            runs_on: "ubuntu-22.04"
            extra_flags: ""
          - name: "Ubuntu 20.04, Py 3.8"
            distro_image: "ubuntu:20.04"
            extra_flags: ""
          - name: "Ubuntu 22.04 Py 3.10"
            distro_image: "ubuntu:22.04"
            extra_flags: ""
          - name: "Ubuntu 22.04, Py 3.10, from main"
            distro_image: "ubuntu:22.04"
            extra_flags: --upgrade-from=main
          - name: "Ubuntu 22.04, Py 3.10, from latest"
            distro_image: "ubuntu:22.04"
            extra_flags: --upgrade-from=latest
          - name: "Ubuntu 22.04, Py 3.10, from 0.2.0"
            distro_image: "ubuntu:22.04"
            extra_flags: --upgrade-from=0.2.0

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install integration-tests/requirements.txt
        run: pip install -r integration-tests/requirements.txt

      - name: Run bootstrap tests (Runs in/Builds ${{ matrix.distro_image }} derived image)
        run: |
          pytest integration-tests/test_bootstrap.py
        timeout-minutes: 10
        env:
          # integration-tests/test_bootstrap.py will build and start containers
          # based on this environment variable. This is similar to how
          # .github/integration-test.py build-image can take a --build-arg
          # setting the base image via a Dockerfile ARG.
          BASE_IMAGE: ${{ matrix.distro_image }}

      - name: Build systemd image, derived from ${{ matrix.distro_image }}
        run: |
          .github/integration-test.py build-image \
              --build-arg "BASE_IMAGE=${{ matrix.distro_image }}"

      # Overview of how this logic influences the end result.
      # - integration-test.yaml:
      #
      #   - Runs integration-test.py build-image, to build a systemd based image
      #     to use later.
      #   - Runs integration-test.py run-tests, to start a systemd based
      #     container, run the bootstrap.py script inside it, and then run
      #     pytest from the hub python environment setup by the bootstrap
      #     script.
      #
      - name: pytest integration-tests/
        run: |
          .github/integration-test.py run-test basic-tests \
              ${{ matrix.extra_flags }} \
              test_hub.py \
              test_proxy.py \
              test_install.py \
              test_extensions.py
        timeout-minutes: 10
      - name: show logs
        run: |
          .github/integration-test.py show-logs basic-tests

      - name: pytest integration-tests/test_admin_installer.py
        run: |
          .github/integration-test.py run-test admin-tests \
              --installer-args "--admin admin:admin" \
              ${{ matrix.extra_flags }} \
              test_admin_installer.py
        timeout-minutes: 5
      - name: show logs
        run: |
          .github/integration-test.py show-logs admin-tests

      - name: pytest integration-tests/test_simplest_plugin.py
        run: |
          .github/integration-test.py run-test plugin-tests \
              --installer-args "--plugin /srv/src/integration-tests/plugins/simplest" \
              ${{ matrix.extra_flags }} \
              test_simplest_plugin.py
        timeout-minutes: 5
      - name: show logs
        run: |
          .github/integration-test.py show-logs plugin-tests
